# Site settings
title: Creative[Tech]
header-img: img/home-bg.png
email: read.musik@gmail.com
copyright_name: AReid987
description: > # this means to ignore newlines until "baseurl:"
  "Hello World!"
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  AReid987
learn_profile: AReid987
email_username: read.musik@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
